package top.saltwood.dologger.database;

import com.mojang.logging.LogUtils;
import org.slf4j.Logger;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class SchemaCreator {
    private static final Logger LOGGER = LogUtils.getLogger();

    private SchemaCreator() {
    }

    public static void createSchema(Connection connection) throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            createUserTables(stmt);
            createLevelTables(stmt);
            createMaterialTables(stmt);
            createEntityTables(stmt);
            createHistoryTables(stmt);
            migrateHistoryTables(stmt);
            createIndexes(stmt);
        }
        LOGGER.info("DoLogger: Database schema verified/created");
    }

    public static String onConflictDoNothing() {
        return "ON CONFLICT DO NOTHING";
    }

    public static String onConflictDoUpdate(String conflictColumns, String updateAssignments) {
        return "ON CONFLICT (" + conflictColumns + ") DO UPDATE SET " + updateAssignments;
    }

    public static String identityColumn() {
        return "integer GENERATED BY DEFAULT AS IDENTITY";
    }

    public static String binaryType() {
        return "bytea";
    }

    private static void createUserTables(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL,
                    uuid uuid DEFAULT NULL UNIQUE
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS usernames (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    time bigint NOT NULL,
                    uuid uuid NOT NULL,
                    name varchar(16) NOT NULL,
                    UNIQUE(uuid, name)
                )
                """);
    }

    private static void createLevelTables(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS levels (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL UNIQUE
                )
                """);
    }

    private static void createMaterialTables(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS materials (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL UNIQUE
                )
                """);
    }

    private static void createEntityTables(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS entities (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL UNIQUE
                )
                """);
    }

    private static void createHistoryTables(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS blocks (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    type integer NOT NULL,
                    action integer NOT NULL,
                    reverted_at bigint NULL,
                    reverted_by integer NULL REFERENCES users(id),
                    restored_at bigint NULL,
                    restored_by integer NULL REFERENCES users(id),
                    revert_batch uuid NULL,
                    restore_batch uuid NULL,
                    command_generated boolean NOT NULL DEFAULT false,
                    source_block_id integer NULL REFERENCES blocks(id)
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS containers (
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    type integer NOT NULL,
                    data bytea,
                    amount integer NOT NULL,
                    action integer NOT NULL
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS items (
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    type integer NOT NULL,
                    data bytea,
                    amount integer NOT NULL,
                    action integer NOT NULL
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS sessions (
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    action integer NOT NULL
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS chats (
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    message varchar(256) NOT NULL
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS commands (
                    time bigint NOT NULL,
                    user_id integer NOT NULL REFERENCES users(id),
                    level integer NOT NULL REFERENCES levels(id),
                    x integer NOT NULL,
                    y integer NOT NULL,
                    z integer NOT NULL,
                    command varchar(256) NOT NULL
                )
                """);
    }

    private static void migrateHistoryTables(Statement stmt) throws SQLException {
        stmt.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'blocks'
                          AND column_name = 'id'
                    ) THEN
                        ALTER TABLE blocks ADD COLUMN id integer;
                        CREATE SEQUENCE IF NOT EXISTS blocks_id_seq OWNED BY blocks.id;
                        ALTER TABLE blocks ALTER COLUMN id SET DEFAULT nextval('blocks_id_seq');
                        UPDATE blocks SET id = nextval('blocks_id_seq') WHERE id IS NULL;
                        PERFORM setval('blocks_id_seq', COALESCE((SELECT MAX(id) FROM blocks), 0) + 1, false);
                        ALTER TABLE blocks ALTER COLUMN id SET NOT NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'blocks'::regclass
                          AND contype = 'p'
                    ) THEN
                        ALTER TABLE blocks ADD PRIMARY KEY (id);
                    END IF;
                END
                $$
                """);
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS reverted_at bigint NULL");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS reverted_by integer NULL REFERENCES users(id)");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS restored_at bigint NULL");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS restored_by integer NULL REFERENCES users(id)");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS revert_batch uuid NULL");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS restore_batch uuid NULL");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS command_generated boolean NOT NULL DEFAULT false");
        stmt.execute("ALTER TABLE blocks ADD COLUMN IF NOT EXISTS source_block_id integer NULL REFERENCES blocks(id)");
    }

    private static void createIndexes(Statement stmt) throws SQLException {
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_time ON blocks(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_user ON blocks(user_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_level_coords ON blocks(level, x, y, z)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_type ON blocks(type)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_action ON blocks(action)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_revert_candidates ON blocks(level, action, command_generated, reverted_at, time DESC, id DESC)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_restore_candidates ON blocks(level, action, command_generated, reverted_at, restored_at, time ASC, id ASC)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_blocks_source_block_id ON blocks(source_block_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_containers_time ON containers(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_containers_user ON containers(user_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_items_time ON items(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_items_user ON items(user_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_sessions_time ON sessions(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_chats_time ON chats(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_chats_user ON chats(user_id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_commands_time ON commands(time)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_commands_user ON commands(user_id)");
    }
}
